apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  labels: 
   release: prometheus-stack
  name: blackbox-exporter
  namespace: monitoring
spec:
  jobName: http-get
  interval: 60s
  module: http_2xx
  prober:
    url: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
    scheme: http
    path: /probe
  targets:
    staticConfig:
      static:
      - https://app.kevtamariz.tk
      - https://monitor.kevtamariz.tk