apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    chart: kube-prometheus-stack
    helm:
      values: |
        grafana: 
          ingress:
            enabled: true
            annotations: 
              kubernetes.io/ingress.class: "nginx"
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - monitor.kevtamariz.tk
            path: /
            tls: 
              - secretName: grafana-general-tls
                hosts:
                  - monitor.kevtamariz.tk
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 42.0.1