apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  project: default
  source:
    path: k8/dev/app
    repoURL: https://github.com/applaudo-gcp-tp/ktamariz_finalproject_express-mongodb-crud.git
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: app