name: Docker build and push - App2

on:
  push:

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login Docker
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
      - name: Docker build
        env:
          DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_REPO }}
        run: |
          docker build -t $DOCKERHUB_REPO:app2.v1.0.0  .
      - name: Docker push
        env:
          DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_REPO }}
        run: |
          docker push $DOCKERHUB_REPO:app2.v1.0.0